### GET request with a header
GET http://localhost:8081/api/v1/airplanes
Accept: application/json

### GET request with a header
GET http://localhost:8081/api/v1/airplanes/2
Accept: application/json

### Send POST request with json body
POST http://localhost:8081/api/v1/airplanes
Content-Type: application/json

{
  "id": "4",
  "name": "content",
  "code": "000004",
  "description": "description4"
}